# Generated by Django 3.1 on 2020-08-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='text0',
            new_name='texto',
        ),
    ]
